#!/bin/bash
#SBATCH --job-name=myjob # the name of your job
#SBATCH --output=/scratch/ss3526/marshoutput.txt # this is the file your output and errors go to
#SBATCH --time=20:00 # 20 min, shorter time, quicker start, max run time
#SBATCH --workdir=/scratch/ss3526 # your work directory
#SBATCH --mem=2000

module load matlab
matlab -nodisplay -nodesktop -r "run /Datadisk/mcevoyd/spi_spei_auto/get_HCN_data.m"
